CREATE DATABASE BALAJI
USE BALAJI
CREATE TABLE STUDENTS(ROLLNO INT , NAME VARCHAR(18) , CITY VARCHAR(12) )
DROP TABLE STUDENTS
SELECT * FROM STUDENTS
INSERT INTO STUDENTS (ROLLNO, NAME ,CITY ) VALUES(1001,'BALA','CHENNAI')
INSERT INTO STUDENTS VALUES(1002,'SURYA','PORUR')
SELECT * FROM Syslockinfo
SP_HELP STUDENTS;
SELECT USER_NAME(10)
CREATE TYPE DOB FROM VARCHAR(10) NOTNULL
DROP TYPE DOB 